extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - inset
        - place-content
  media-feature-range-notation:
    - prefix
  no-descending-specificity: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - icon
        - page
        - picker
        - scroll-view
  shorthand-property-no-redundant-values: null
