extends:
  - stylelint-config-hope
rules:
  media-feature-range-notation:
    - prefix
  no-descending-specificity: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - page
        - picker
  shorthand-property-no-redundant-values: null
