extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - inset
        - flex-flow
        - place-content
  media-feature-range-notation:
    - prefix
  no-descending-specificity: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - icon
        - navigator
        - page
        - picker
        - scroll-view
        - swiper
        - radio
        - wx-root-portal-content
  shorthand-property-no-redundant-values: null
  unit-no-unknown:
    - true
    - ignoreUnits:
        - rpx
