name: Build Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Build Wechat project
        run: pnpm build:wx

      - name: Build QQ project
        run: pnpm build:qq

      - name: Build Nenuyouth project (Wechat)
        run: pnpm build:qy

      - name: Build App
        run: pnpm build:app

      - name: Linter test
        run: pnpm lint
