name: Build Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm ci

      - name: Build Wechat
        run: pnpm run build:wx

      - name: Build weNENU
        run: pnpm run build:we

      - name: Build App
        run: pnpm run build:app

      - name: Linter test
        run: pnpm run lint
